environment:
  nodejs_version: "6"
services:
  - mongodb
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --ignore-scripts
  - npm install granax
test_script:
  - npm test
build: off
before_deploy:
  - npm remove electron-prebuilt-compile
  - npm install electron-prebuilt-compile
  - npm run make-win
deploy:
  description: 'automatic draft release'
  provider: GitHub
  auth_token:
    secure: lN8A7/iiIPrWb0iJ4P2wvJUQ7qG7r6b2qxkMFN/pUNaMlyxck/hz1ba6/0oqYKoN
  artifact: /out\make\squirrel.windows\*.exe/
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
platform: x64
