language: node_js
os:
  - linux
  - osx
services:
  - mongodb
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
node_js:
  - "6.11.5"
before_install: ./script/preinstall-ci.sh
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
