version: '2'
services:
  orcd:
    build:
      context: .
      dockerfile: ./Dockerfile.simulation
    volumes:
      - ./bin:/root/orc/bin
      - ./lib:/root/orc/lib
      - ./web:/root/orc/web
      - ./test:/root/orc/test
      - ./index.js:/root/orc/index.js
      - ./node_modules:/root/orc/node_modules
      - ./package.json:/root/orc/package.json
      - ~/.config/orcd.simulation/main:/root/.config/orcd
    ports:
      - "127.0.0.1:9089:9089"
