version: '2'
services:
  orc:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./lib:/root/orc/lib
      - ./test:/root/orc/test
      - ~/orc:/root/.config/orc
    ports:
      - "4444:4444"
      - "4445:4445"
      - "4446:4446"
    environment:
      - .env
