version: '2'
services:
  orcd:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./bin:/root/orc/bin
      - ./lib:/root/orc/lib
      - ./web:/root/orc/web
      - ./test:/root/orc/test
      - ./index.js:/root/orc/index.js
      - ./node_modules:/root/orc/node_modules
      - ./package.json:/root/orc/package.json
      - ~/.config/orcd.dev:/root/.config/orcd
    ports:
      - "127.0.0.1:9088:9088"
      - "127.0.0.1:9089:9089"
      - "127.0.0.1:37017:37017"
    environment:
      - .env
